"""
precompute_overlays.py
----------------------
Converts all 67 prediction .tiff files already generated by run_full_evaluation.py
into colored PNG heatmaps with their GPS bounds.

Reads:  test/outputs_full_eval/pred_*.tiff  (flood class mask)
Writes: backend/static/overlays/{image_id}.png  (blue transparent flood heatmap)
        backend/static/overlays/manifest.json   (list of image_id + bounds + metrics)

Run once: d:/AdvayaHakcathon/venv/Scripts/python.exe backend/precompute_overlays.py
"""

import json
import csv
import numpy as np
from pathlib import Path
from PIL import Image
import rasterio
from rasterio.warp import transform_bounds
from rasterio.crs import CRS

WORKSPACE = Path("D:/AdvayaHakcathon")
PRED_DIR  = WORKSPACE / "test" / "outputs_full_eval"
CSV_PATH  = PRED_DIR / "full_results.csv"
OUT_DIR   = WORKSPACE / "backend" / "static" / "overlays"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Flood colour: solid blue at 60% opacity
FLOOD_RGBA  = (30, 130, 255, 160)
WATER_RGBA  = (0,   80, 200, 100)  # Slightly darker for class 1 confidence


def pred_tiff_to_png(tiff_path: Path, out_png: Path) -> dict | None:
    """
    Reads a prediction .tiff (values 0=no flood, 1=flood, -1=nodata),
    creates a transparent PNG overlay and returns the WGS84 bounding box.
    """
    try:
        with rasterio.open(tiff_path) as src:
            data = src.read(1)  # shape (H, W)

            # Get geographic bounding box in WGS84
            bounds = src.bounds
            if src.crs is None:
                print(f"  [SKIP] {tiff_path.name} — no CRS info")
                return None

            wgs84 = CRS.from_epsg(4326)
            if src.crs != wgs84:
                left, bottom, right, top = transform_bounds(
                    src.crs, wgs84,
                    bounds.left, bounds.bottom, bounds.right, bounds.top
                )
            else:
                left, bottom, right, top = bounds.left, bounds.bottom, bounds.right, bounds.top

        H, W = data.shape
        rgba = np.zeros((H, W, 4), dtype=np.uint8)

        # Flood pixels are encoded as 255 by inference.py (not 1)
        flood_mask = (data == 255)
        rgba[flood_mask] = FLOOD_RGBA

        # Save
        Image.fromarray(rgba, mode="RGBA").save(out_png)

        flood_pct = float(flood_mask.sum()) / float(H * W) * 100

        return {
            "bounds": [[bottom, left], [top, right]],   # Leaflet format [[s,w],[n,e]]
            "flood_pct": round(flood_pct, 2),
        }

    except Exception as e:
        print(f"  [ERROR] {tiff_path.name}: {e}")
        return None


def load_metrics() -> dict:
    """Build a dict of image_id -> metrics from the CSV."""
    metrics = {}
    if not CSV_PATH.exists():
        return metrics
    with open(CSV_PATH, newline="") as f:
        for row in csv.DictReader(f):
            metrics[row["image_id"]] = {
                "accuracy": float(row.get("accuracy", 0)),
                "f1":       float(row.get("f1", 0)),
                "iou":      float(row.get("iou", 0)),
            }
    return metrics


def main():
    metrics = load_metrics()
    pred_tiffs = sorted(PRED_DIR.glob("pred_*.tiff"))
    print(f"Found {len(pred_tiffs)} prediction tiffs. Converting...\n")

    manifest = []
    for tiff_path in pred_tiffs:
        # Extract image_id from filename like "pred_989230_6band.tiff"
        name = tiff_path.stem  # e.g. pred_989230_6band
        parts = name.split("_")
        image_id = parts[1] if len(parts) >= 2 else name

        out_png = OUT_DIR / f"{image_id}.png"
        print(f"  Processing {image_id}...", end=" ")

        result = pred_tiff_to_png(tiff_path, out_png)
        if result is None:
            print("SKIPPED")
            continue

        entry = {
            "image_id":  image_id,
            "png_url":   f"/static/overlays/{image_id}.png",
            "bounds":    result["bounds"],
            "flood_pct": result["flood_pct"],
        }
        if image_id in metrics:
            entry.update(metrics[image_id])

        manifest.append(entry)
        print(f"OK  (flood {result['flood_pct']:.1f}%)")

    manifest_path = OUT_DIR / "manifest.json"
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\nDone! {len(manifest)} overlays written.")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
